### ISSUE TITLE
Can't reach to gamebot

### ISSUE THREAD

**Issue by FakeID01** [ClashGameBot/CGB#4]
Can't access to CGB's website and forum
![cgb ssl](https://cloud.githubusercontent.com/assets/14106742/9654479/a802f92e-525d-11e5-802a-502d90e4f28b.png)

Even the Facebook page isn't available
![cgb fb](https://cloud.githubusercontent.com/assets/14106742/9654576/3e85a50e-525e-11e5-8928-353f90213f23.png)

Please help!

**Comment by napsterv** [comment]
Phewww. I thought I was the only one.

**Comment by FakeID01** [comment]
A few of my friends are facing this too.
@napsterv Is the FB page working for you?

**Comment by kaganus** [comment]
we will be back, probably under a different name, dont worry, we'll notify you :)

**Comment by napsterv** [comment]
@FakeID01 Nope. Looks like they deleted their FB page.

**Comment by FakeID01** [comment]
@napsterv Okay, good to know.
@kaganus Thank you for informing us here. Can you guys release the news somewhere so that CGB users will know about this?

**Comment by napsterv** [comment]
@kaganus Thanks for the update. I thought you guys shut down or something.

**Comment by shariqriaz** [comment]
Nice to know u guys are still working :) what happened though?

**Comment by kaganus** [comment]
well details should be revealed when we are ready i think :)

**Comment by shariqriaz** [comment]
Hope to see u guys live back soon

**Comment by napsterv** [comment]
@FakeID01 @shariqriaz https://github.com/kaganus/cgb-modded/pull/41

**Comment by FakeID01** [comment]
Oh thanks @napsterv didnt knew about that issue. Will close this issue now.
Go to https://github.com/kaganus/cgb-modded/pull/41 for any other issues related to the CGB website.

**Comment by KnowJack20** [comment]
The founder code named "Envyus" claims he was hacked, but won't show any proof that it actually happened.  He has control of the DNS registration, forwarded the DNS servers into blank server space, and disappeared. He has taken the registered names clashgamebot.org and gamebot.org with him. Clashgamebot.org is now listed for sale on the GoDaddy online name auction site. 
The event created all kinds of mistrust within the team. DixonHill refused to believe Envyus was hacked, and was booted from a new team while waiting on proof before passing judgment.  Several juvenile actions by the admins "Dinobot" and "Neptune" during the episode reminded many that the former team was born from a admitted Java hacking site, and trust was a rare commodity.  I got tired with their fear mongering and name calling, so I decided I could not work with them any longer.  If you have an account on gamebot.org, make sure the ID and password are truly unique and not repeated anywhere.  You might be the next victim of the admins mayhem.
I am posting this here as the admins will block me and the truth from the site when it comes back up.

**Comment by napsterv** [comment]
@KnowJack20 Wow. Shit just got serious .

**Comment by shariqriaz** [comment]
Wow... I just lost hope

**Comment by SmokE-PGF** [comment]
@KnowJack20 well that sucks hope you come back if there is a new site and a solid team.

Let us know if there is a site or anything that comes up @kaganus 
Such a shame to throw a decent project out just because of a few admins being immature

**Comment by kaganus** [comment]
its not exactly as jack explained. its correct up to the part with DixonHill. dixon was not ditched because he refuse to believe anything, but because he was always trying to have power among the team (since long before any of this shit happened) by using fancy words and by trying to impose we needed a leader and he was the perfect candidate for it. his rash actions with little power he had revealed his true self, thats why many of the developers didnt want him in the new happening. not to mention his contribution to the bot as a dev or anything else was not much tbh.

as for admins "juvenile" actions, it is correct they behave childish sometimes, but that is because of their age. and since admin has no control over anything, they wont create any problems, and i trust all they want is to have fun doing what we do. in times like these, people can become irritated, angry, and not act mature, but its just a phase. btw the title admin will change to webmaster not to confuse our users, since admins are not the people who have the last say in things, just web keepers (forum server etc. maintenance)

we are still waiting for envyus' proof as he told us he would supply this weekend, but nevertheless we decided we needed more people with access to key elements like domain control, web server etc. and envyus did not have any intention of sharing that, so we had to move on to a new name for now. if he is able to supply proving documents to support his case and the trust is earned again, theres no reason he shouldnt be able to join again.

but in the end we experienced what happens when only 1 person is in control (hacked or not), and we do not want that so we had to revise our organization

im still sorry how jack thinks about it all, but all the decisions taken were to continue what we do with the same community.

and as i said before, when the time is ready we'll have an anouncement, it wasnt a good idea to reveal things that were not concluded yet by jack. whats done it done, no need to panic, we are still in control, if anything bad happens, ill tell you guys when to panic (if ever) :)

**Comment by promac2k** [comment]
Good words kaganus , we need a couple of days to finish our plan , and open the site again.

**Comment by KnowJack20** [comment]
Good words Kaganus!  I just wished you used that same fair minded attitude during the whole ordeal that caused you to get temporary removed due the in-fighting and the witch hunt for a instant answer on whether Envyus was hacked or not.  But like a few other occasions, I guess you and I will just have to agree to disagree on the proper words to describe the truth and how well everyone handled it.  
I have no ill will to anyone, enjoyed working with the team, and wish everyone the best.:)

PS -There is now reason to worry about the bot.  Several of the long time developers are re-energized and are working hard to restart the work on a different domain and with a different name. I won't spoil the surprise, but if you look really hard on Google you find it. :)
Cheers!

**Comment by DixonHill** [comment]
@kaganus 
I'm sure folks would want to know both sides of the issue on account of DixonHill.  I'm one of the few folks who founded and organized GameBot when we split off of TBC. I'm also one of the few people that were trying to calm folks down when Envyus went MIA.  Much ugliness ensued and much rudeness exchanged.  Two of my actions that alienated some of the team members: 1) My calls for giving Envyus a temporary benefit of the doubt till we see proof of his being hacked, and 2) excluding one of the members from the Slack discussion groups due to his unrestrained insults.  Unlike Kaganus, I don't believe that there is anything wrong in "using fancy words" or trying to take initiative and calm folks down (what he calls "trying to impose we needed a leader").  I do however believe that in order for a team to function, it needs these important ingredients: professionalism, organization and good will, and what we ended up with was missing all of them.  That's the reason Jack stepped out, and that's the reason that I wouldn't work in these conditions even if I was paid handsomely.
P.S. Kaganus, I know that you are capable of having good will when you control your temper, and I recommend staying away from personal attacks.  I consider attacking someone's reputation  in public as dishonorable.  Neither you nor most of the new members of CGB knew the full scope of my contributions to the team, so your description of what I've put in could possibly be quite inaccurate.

**Comment by kaganus** [comment]
well as you said, you have your own point of view, i have mine, so does others. lets let people decide for themselves

**Comment by vhung85** [comment]
Dmitry(DixonHill), could u let me know for me what feature u did on the bot?
You didn't , or not yet contribute to GB. You only create a slack team, so we can working together, and disappear and several times belong with envyus.
When have any fight with envyus, u using the owner slack permission to kick us out.
U said : u are one of the few folks who founded and organized GameBot when we split off of TBC. 
Yes, and me too ,dinobot too
What u think when kick us out from slack?
And honestly  an incompetence like u should go away from GB asap.

**Comment by gyrex** [comment]
Sorry to hear about all the political garbage guys. I was a donor and it's a shame to see what's happened. I'd be happy to buy a domain name and run a server for you if you like? Contact me if you want some help getting this running under a different name... Got a shared server in the US we could use and I'm happy to buy a domain name for you.
